//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Tecnico_Suc_Ele
    {
        public int id_tecnico { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public Nullable<decimal> sueldo_base { get; set; }
        public string nombre_sucursal { get; set; }
        public string elementos { get; set; }
    }
}
